# Generated by Django 4.0.4 on 2022-04-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kategoriya nomini kiriting...', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mahsulot nomini kiriting', max_length=400)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(help_text='Mahsulot haqida kiriting...')),
                ('image', models.ImageField(upload_to='products')),
                ('discount', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': 'Product ',
                'verbose_name_plural': 'Products ',
            },
        ),
    ]
