# Generated by Django 4.0.4 on 2022-04-21 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, null=True)),
                ('adress', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=400, null=True)),
                ('state', models.CharField(max_length=400, null=True)),
                ('zipcode', models.CharField(max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer ',
                'verbose_name_plural': 'Customers ',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.IntegerField(default=2305)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
            options={
                'verbose_name': 'Order ',
                'verbose_name_plural': 'Orders ',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category ', 'verbose_name_plural': 'Categories '},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.products')),
            ],
            options={
                'verbose_name': 'OrderItems ',
                'verbose_name_plural': 'OrderItems ',
            },
        ),
    ]
